version: '3.1'
services:
  form-generator:
    build:
        context: form-generator
    command: yarn run dev
    ports:
      - 8777:8777
    volumes:
      - ./ui:/code
  email-proxy:
    build:
        context: api
    volumes:
      - ./api:/code
    ports:
      - 8888:5000
    environment: 
      MG_KEY: ${MG_KEY} 
